# Sample config used by the development environment
[auth]
source = "aramaki"

[server]
host = "127.0.0.1"
port = 8000

[aramaki]
url = "wss://directory.0e9d93af.largo01.fcdev.fcio.net/aramaki"
state_directory = ".aramaki-workdir"
secret_salt = ""
principal = "kyle00"

[[backend]]
type = "skvaider"
url = "http://127.0.0.1:8001"

[[backend]]
type = "skvaider"
url = "http://127.0.0.1:8002"

[[models]]
id = "gemma"
instances = 2
memory = { ram = "1.3G" }
task = "chat"

[[models]]
id = "embeddinggemma"
task = "embedding"
instances = 1
memory = { ram = "1.4G" }

[logging]
log_level = "DEBUG"
access_log_path = ".access_log"
