# Sample config used by the development environment
models_dir = "var/lib/models-2"

[server]
host = "127.0.0.1"
port = 8002

[logging]
log_level = "DEBUG"
log_dir = "var/log/inference2"

[[openai.models]]
engine = "dummy"
id = "gemma"
task = "chat"
max_requests = 42
port = 8200

[[openai.models]]
engine = "dummy"
id = "embeddinggemma"
task = "embedding"
port = 8201
