# Sample config used by the development environment
models_dir = "var/lib/models-1"
embedding_verification_file = "embeddings-reference.json"

[server]
host = "127.0.0.1"
port = 8001


[logging]
log_level = "DEBUG"
log_dir = "var/log/inference1"

[[openai.models]]
engine = "dummy"
id = "gemma"
task = "chat"
max_requests = 21
port = 8100

[[openai.models]]
engine = "dummy"
id = "embeddinggemma"
task = "embedding"
port = 8101
