# Sample config used by the development environment
[auth]
source = "aramaki"

[aramaki]
url = "wss://directory.0e9d93af.largo01.fcdev.fcio.net/aramaki"
state_directory = ".aramaki-workdir"
secret_salt = ""
principal = "kyle00"

[[backend]]
type = "openai"
url = "http://127.0.0.1:11435"

[logging]
log_level = "DEBUG"
access_log_path = ".access_log"
