# Sample config used by the development environment
models_dir = "models"

[logging]
log_level = "DEBUG"
access_log_path = "access_log"

[openai.models."unsloth/gemma-3-270m-it-GGUF:gemma-3-270m-it-UD-Q4_K_XL"]
# aliases = ["gemma3-270m"] XXX?
url = "https://huggingface.co/unsloth/gemma-3-270m-it-GGUF/resolve/main/gemma-3-270m-it-UD-Q4_K_XL.gguf?download=true"
hash = "e5420636e0cbfee24051ff22e9719380a3a93207a472edb18dd0c89a95f6ef80"
context_size = 4096
cmd_args = []
