# Sample config used by the development environment
[auth]
source = "aramaki"

[aramaki]
url = "wss://directory.b82f1c635cc.largo01.fcdev.fcio.net/aramaki"
state_directory = ".aramaki-workdir"
secret_salt = "foobar"
principal = "asdf"

[[backend]]
type = "openai"
url = "http://127.0.0.1:11435"
