[[models]]
id = "gpt-oss:20b"
object = "model"
created = 1755429880
owned_by = "library"

[[models]]
id = "llava:34b"
object = "model"
created = 1755337894
owned_by = "library"

[[models]]
id = "llama3.2-vision:11b"
object = "model"
created = 1755337676
owned_by = "library"

[[models]]
id = "qwen3:32b"
object = "model"
created = 1755337354
owned_by = "library"
