"""rename

Revision ID: 092d0a531642
Revises: 26d98ade309b
Create Date: 2025-09-04 10:43:17.102021

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "092d0a531642"
down_revision: Union[str, Sequence[str], None] = "26d98ade309b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collection_replication_status") as batch_op:
        batch_op.alter_column(
            "data",
            existing_type=sa.BLOB(),
            type_=sa.JSON(),
            existing_nullable=False,
        )
        batch_op.drop_constraint(
            op.f("collection_partition_unique"),
            type_="unique",
        )
    op.rename_table("collection_replication_status", "collection_record")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("collection_record", "collection_replication_status")

    with op.batch_alter_table("collection_replication_status") as batch_op:
        batch_op.create_unique_constraint(
            op.f("collection_partition_unique"),
            ["collection", "partition"],
        )
        batch_op.alter_column(
            "data",
            existing_type=sa.JSON(),
            type_=sa.BLOB(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
