"""add initial collections

Revision ID: 26d98ade309b
Revises: 483f39694e84
Create Date: 2025-09-02 15:55:19.505803

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26d98ade309b"
down_revision: Union[str, Sequence[str], None] = "483f39694e84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_replication_status",
        sa.Column("collection", sa.String(), nullable=False),
        sa.Column("partition", sa.String(), nullable=False),
        sa.Column("record_id", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("collection", "partition", "record_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("collection_replication_status")
    # ### end Alembic commands ###
