name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nixbuild/nix-quick-install-action@v33
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv
    - name: Set up Python venv
      run: devenv shell uv sync
    - uses: actions/setup-python@v4
    - uses: pre-commit/action@v3.0.0
